---
title: "Bureaucratic discrimination stemming from Islamophobia needs to be highlighted"
subtitle: "My subtitle if needed"
author: 
  - First author
  - Another author
thanks: "Code and data are available at: LINK."
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
```

# Introduction

From the past to the present, bureaucracy has been a characteristic predominantly found in large companies or public institutions. With the nature of bureaucracy, specific individuals or groups within an organization tend to hold the authority to make most administrative decisions, which can result in administrative discrimination stemming from subjective or group opinions or beliefs influencing administrative decisions.

The original study, “The Unequal Distribution of Opportunity: A National Audit Study of Bureaucratic Discrimination in Primary School Acces (2020) by Olsen, Kyhse-Anderson, Moynihan”, experimented with the unequal opportunities brought about by bureaucratic discrimination in Danish primary schools. Before the experiment, Olsen, Kyhse-Anderson, Moynihan defined bureaucratic discrimination as two forms: either through withholding opportunities in service or imposing administrative burdens to make bureaucratic procedures more complex and difficult. As a result, the original study revealed that individuals with Muslim names experience both forms of bureaucratic discrimination more frequently than those with native (Danish) names.

Our paper will reproduce these findings and will focus on the potential administrative discrimination against Muslims in Canada by building on the two forms of administrative discrimination (1. withholding opportunities in service, 2. imposing administrative burdens to make bureaucratic procedures more complex and difficult) Through the original experiment’s results, we discovered that administrative discrimination against Muslims could be driven by Islamophobic attitudes. Based on the two forms of bureaucratic discrimination defined in the original experiment, our study aims to assess perceptions of Muslims in Canada and discuss the potential for widespread administrative discrimination against Muslims.

\newpage

# Data {#sec-data}

## Source

This paper reproduces two results from "The Unequal Distribution of Opportunity: A National Audit Study of Bureaucratic Discrimination in Primary School Access(2020) by Olsen, Kyhse-Anderson, Moyni-han" in the American Journal of Social Science.
In the original study, the results showed disparities in decision type rates, compliance cost rates, and psychological cost rates. 
For the decision type, response emails were classified into three categories: clear reject, unclear response, and clear accept.(Examples 1-4 in Appendix A illustrate unclear responses)
As for compliance cost, it was categorized into four groups based on the format of the email content: simple question, complex question, request a phone call, and request to meet. Since decision type rates and compliance cost rates represent two forms of administrative discrimination above, our study will also verify these two sets of results and discuss the potential administrative discrimination against Muslims in Canada.

## Methodology

The original experiment was conducted with 1,698 primary schools in Denmark, where fictitious emails regarding student transfer requests were sent to each school. These emails were sent under different names (Muslim/Danish), with 850 emails sent under one name and 848 under the other. Fictitious students were also assigned diligence traits, which could be discerned from the content of the emails (Overview of Senders’ and Respondents’ traits). Additionally, the original study examined both the characteristics of the schools and those of the senders. The characteristics of the schools (whether the school is located in a major city, its geographical region, the average student grades, the number of students, the number of non-Danish students, and the school type.) were investigated using the Danish Ministry of Education database, while the characteristics of the senders were determined based on the content of the response emails.

[***Senders trait***]{.underline}

-   **Name**:

    -   Danish: Peter Nielsen

    -   Muslim: Mohammad Osman

-   **Diligence trait**:

    Diligence trait was classified based on the content of the emails, according to the experiment setting in the original study.

    -   Hi \[school name\]. I am writing because we would like to move our son to another school.

        [Non-diligent student treatment]{.underline}: He is in 3rd grade and we don't think that it is going very well at this school

        [Diligent student treatment]{.underline}: He is in 3rd grade and the teachers say that he is doing well with his homework. but we still don't think that it is going very well at this school

[***Respondents'(School) trait***]{.underline}

-   **Major(Big) city**: whether the school is located in a big city

-   **Geographical region**: Reion Hovedstade, Region Midtjylland, Region Nordjylland, Region Sjaelland or Region Syddanmark

-   **School type**: Public or Private

-   **Number of Students**

-   **Number of Non-Danish Students**

-   **Average Grade of Students**



### Effect of Senders and Respondents' trait
Lastly, the original study revealed through the full ordinary least squares (OLS) results that neither the diligence trait nor the characteristics of schools have any influence on the outcome variables (decision type, compliance cost). Consequently, apart from racial characteristics based on two different names, no other traits will be mentioned in this paper.

# Results

Our results are summarized in @tbl-modelresults.

# Discussion

## First discussion point {#sec-first-point}

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this.

## Second discussion point

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

# References
